### ISSUE TITLE
Is Indexing working?

### ISSUE THREAD

**Issue by Breakingx** [codefaux/deemix-for-lidarr#4] opened 2024-03-11 14:25 UTC
Hey, thanks for the project.

Just a question. I successfully setted up the container and everything works. But is the indexer really running?
For example a Song called "Ich Ich Ich" by Alligatoah was released two days ago but it's missing in lidarr.

The indexers connection in Lidarr is correctly tested with deezer but there is this song missing.

**Comment by Breakingx** [comment] 2024-03-11 15:04
These are the logs trying to download:

`[Info] ReleaseSearchService: Searching indexers for [Alligatoah - ICH ICH ICH (2024)]. 1 active indexers 
[Info] DownloadDecisionMaker: Processing 3 releases 
[Warn] LidarrErrorPipeline: NzbDrone.Core.Download.Clients.DownloadClientException: Expected Deemix to add 1 item, got 0 

[v2.1.1.3878] NzbDrone.Core.Download.Clients.DownloadClientException: Expected Deemix to add 1 item, got 0
   at NzbDrone.Core.Download.Clients.Deemix.DeemixProxy.Download(String url, Int32 bitrate, DeemixSettings settings)
   at NzbDrone.Core.Download.Clients.Deemix.Deemix.Download(RemoteAlbum remoteAlbum, IIndexer indexer)
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteAlbum remoteAlbum, IDownloadClient downloadClient) in ./Lidarr.Core/Download/DownloadService.cs:line 96
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteAlbum remoteAlbum) in ./Lidarr.Core/Download/DownloadService.cs:line 61
   at Lidarr.Api.V1.Indexers.ReleaseController.DownloadRelease(ReleaseResource release) in ./Lidarr.Api.V1/Indexers/ReleaseController.cs:line 130
   at lambda_method199(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Lidarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Lidarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Lidarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Lidarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Lidarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Lidarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


[Fatal] LidarrErrorPipeline: Request Failed. POST /api/v1/release 

[v2.1.1.3878] NzbDrone.Core.Download.Clients.DownloadClientException: Expected Deemix to add 1 item, got 0
   at NzbDrone.Core.Download.Clients.Deemix.DeemixProxy.Download(String url, Int32 bitrate, DeemixSettings settings)
   at NzbDrone.Core.Download.Clients.Deemix.Deemix.Download(RemoteAlbum remoteAlbum, IIndexer indexer)
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteAlbum remoteAlbum, IDownloadClient downloadClient) in ./Lidarr.Core/Download/DownloadService.cs:line 96
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteAlbum remoteAlbum) in ./Lidarr.Core/Download/DownloadService.cs:line 61
   at Lidarr.Api.V1.Indexers.ReleaseController.DownloadRelease(ReleaseResource release) in ./Lidarr.Api.V1/Indexers/ReleaseController.cs:line 130
   at lambda_method199(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Lidarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Lidarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Lidarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Lidarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Lidarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Lidarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)`

**Comment by codefaux** [comment] 2024-03-11 22:31
So, the short answer is yes, Indexing is working. Releases under a week old will be problematic with any Lidarr instance.

The longer answer is, I suspect you might misunderstand the role of indexing, and the problem in this case lies in Lidarr's Metadata source which updates periodically, I'm guessing weekly. I don't mean to sound condescending with the below explanation, I'm mostly being thorough so I can refer to it in future cases. My aim is to fill in gaps which anyone might have, not necessarily targeted directly at you. Thank you for understanding.

I'll clarify some Lidarr items which are sometimes not fully understood;

- `Metadata providers` tell Lidarr about artist/album structure, durations, track names, etc. Without `Metadata`, Lidarr can't do anything related to a particular artist, album, or song. It can't know it exists, thus it can't search for it, import it if you have it, it can't pull it from an `RSS feed`, it won't respond properly to an `Indexer` request, and it won't import it from a `download client`. ( _Metadata is not provided by Deemix or Deezer, and thus out of scope of this project._ ) Lidarr _appears_ to use their own API which is linked to a Lidarr-operated Musicbrainz DB clone which is synchronized intermittently against the public Musicbrainz DB, likely to reduce server load on the official source and avoid being banned as a client. I don't know how often this synchronization occurs, I can't imagine it being less often than weekly. It appears you can provide your own Musicbrainz DB instance if the delay is unacceptable, but I'm unable to comment on doing so. If you're interested, see [here](https://github.com/Lidarr/LidarrAPI.Metadata)

- `RSS feeds` tell Lidarr which things have recently become available on an `Indexer` or platform (ie, Usenet indexers, Torrent sites, etc) and there is no RSS source for Deezer or via Deemix. If you wish to auto-pull new releases, you will need an indexer which provides an RSS feed, which most Usenet or Torrent providers do. I know of no indexer for legally sourced content ie Deezer etc ( _Thus, RSS is not provided by Deemix or Deezer, and thus is out of scope of this project._ )

- `Indexers` take `Metadata` references from Lidarr (track name, count, length, etc) during searches (when applicable) and indicate how to ask a `Download Client` for files matching any results they contain. Most Indexers also provide RSS. Deemix/Deezer do not, which I mentioned already. (`Deemix serves as an Indexer for Search only -- automatic or manual -- and uses Deezer as its sole source for matches.`) Without `Metadata`, Lidarr is unable to tie the ends together, and searches may appear but not import, or may not appear, or may import incorrectly, etc -- so _lots of issues arise here._ I do not remember for certain which Metadata source Lidarr uses, but I hear reports that it can be slow to add newly released items. I don't know at what pace Deezer provides new releases, but this also is a dependent factor.

- `Download Clients` take requests from `Indexers`, and produce files. Everyone's familiar with waiting for releases to show up on platforms, so I won't bother with this part. _Deemix serves as the Download Client for the Deezer platform._


With the basics out of the way -- general troubleshooting should start by opening the Deemix WebUI. See if searches produce results as expected there, and wether or not a download was queued/completed/etc on the sidebar. This can narrow down issues to Deezer or Deemix, instead of the Lidarr interface.

Secondarily, Lidarr uses Metadata Profiles, which limit which results appear under a given Artist, if said Artist is added directly. Ensure you have a Metadata Profile added which includes the types of releases you want. (Album, EP, Single, etc etc) I generally add several depending on the artist. Album+Studio, Album+Singles+Studio, Broad (Album+Singles+EP+Soundtrack+Studio), and Everything (all) that way I can limit the clutter depending on how much I like an artist.

And as a final note; if you're ONLY using Lidarr for Deezer sourced items (ie, if you don't want to use Torrents/Usenet as a source) you can skip Lidarr and just use Deemix. It's not quite the same interface, but it serves essentially the same purpose as the Lidarr+Deemix stack when Torrents/Usenet are excluded, and requires less overhead. You might even enjoy the interface more. If interested, use your web browser to connect to the Docker container's port.

OK. That's the general stuff.

Specifically @Breakingx -- I'm not fully certain how to interpret this. If I'm making an educated guess correctly, this implies that Lidarr has sent a request to the Download Client, and that request has not appeared in the Download Client's queue or that request returned an error. I'm not a Lidarr dev, so I can't begin to diagnose or troubleshoot this specific issue. When adding Alligatoah to my own library, the ICH ICH ICH single does not show in Lidarr's list. This means Lidarr's Metadata provider does not have the track in its database, and Lidarr will be unable to act on this release in any way for now. When Lidarr shows 'ICH ICH ICH' under Singles for 'Alligatoah' (also dependant upon the Metadata Profile used for Alligatoah) I suspect everything will resolve on this issue. This should happen when the public Lidarr API instance synchronizes against the public Musicbrainz instance, which I guess to happen weekly.

Please feel free to comment/ask further if necessary. If you believe this covers it, feel free to close the issue.

**Comment by codefaux** [comment] 2024-03-26 20:33
Since I was around, I checked into it, and I was correct -- Lidarr's upstream metadata has reached its sync interval, ICH ICH ICH is listed as a Single by Alligatoah, and everything works properly with the Deemix integration.

The problem was Lidarr's upstream metadata was out of sync. This is almost always going to be the cause of issues with newly released music. Closing issue, but leave a comment if you need to.

**Closed by codefaux** 2024-03-26 20:33 UTC
